name: autocode_cli
description: A command line interface for Autocode.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  path: ^1.9.1
  ac_blueprints:
    path: ../autocode-dart/packages/ac_blueprints
  ac_documentation:
    path: ../autocode-dart/packages/ac_documentation
  ac_extensions:
    path: ../autocode-dart/packages/ac_extensions
  autocode:
    path: ../autocode-dart/packages/autocode

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
